name: Notification on push

on:
  [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: Github Site do Bem
      uses: Ilshidur/action-discord@master
      with:
        args: {{ EVENT_PAYLOAD.sender.avatar_url }} create event ${{ github.event_name }} event triggered first step in {{ EVENT_PAYLOAD.repository.full_name }}.
        color: "#FFD600"
