name: Notification on push

on:
  [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: Github Site do Bem
      uses: Ilshidur/action-discord@master
      with:
        args: The ${{ github.event_name }} event triggered first step.
        color: "#FFD600"
